var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/batch-image-editor/batches/[batchId]/route.js")
R.c("server/chunks/[root-of-the-server]__61ef0363._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/ce889_server_app_api_batch-image-editor_batches_[batchId]_route_actions_7cffab25.js")
R.m(330856)
module.exports=R.m(330856).exports
