var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/1688-extractor/files/[name]/keywords/route.js")
R.c("server/chunks/[root-of-the-server]__0bc84f38._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__58e47283._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/ce889_server_app_api_1688-extractor_files_[name]_keywords_route_actions_8f0dfc22.js")
R.m(144336)
module.exports=R.m(144336).exports
