export const ORDER_IMPORT_HEADERS = [
  "Sales Channel ID",
  "Quantity",
  "Order number",
  "Customer Name",
  "Customer address",
  "Customer zip code",
  "Customer city",
  "Customer cell phone",
  "Sales Channel Readable name",
  "Customer email",
  "Marketplace order number",
  "Sales channel order number",
  "SKU",
  "Ignore",
  "Ignore2",
  "Transaction Date",
  "Sales value EUR",
  "Date shipped",
  "Ignore3",
  "Ignore4",
  "Ignore5",
  "Ignore6",
  "Ignore7",
  "Ignore8",
  "Tracking number",
] as const;

