var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/products/route.js")
R.c("server/chunks/[root-of-the-server]__2f31d608._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_81516655.js")
R.c("server/chunks/lib_meili_ts_1753ab05._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_products_route_actions_9a81c53e.js")
R.m(486577)
module.exports=R.m(486577).exports
