var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/drafts/folders/[run]/spu-status/route.js")
R.c("server/chunks/[root-of-the-server]__dbd7c8b4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/lib_drafts_ts_8dd19890._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/ce889_server_app_api_drafts_folders_[run]_spu-status_route_actions_5da07fcc.js")
R.m(57091)
module.exports=R.m(57091).exports
