var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/product-delivery/digideal/lists/items/route.js")
R.c("server/chunks/[root-of-the-server]__892388d2._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/ce889_server_app_api_product-delivery_digideal_lists_items_route_actions_449d7c97.js")
R.m(982512)
module.exports=R.m(982512).exports
