var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c2d2b217._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_d2dde2b2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b021ab0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2e5d1b2c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f2037052._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_27de1937._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_admin_page_actions_05aa00d6.js")
R.m(881016)
module.exports=R.m(881016).exports
