var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/drafts/products/delete/route.js")
R.c("server/chunks/[root-of-the-server]__c4196ea0._.js")
R.c("server/chunks/[root-of-the-server]__0bc84f38._.js")
R.c("server/chunks/lib_drafts_ts_8dd19890._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/_next-internal_server_app_api_drafts_products_delete_route_actions_03f93b58.js")
R.m(813986)
module.exports=R.m(813986).exports
