var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/drafts/zip/route.js")
R.c("server/chunks/[root-of-the-server]__e83f45f6._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/lib_drafts_ts_8dd19890._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_drafts_zip_route_actions_8f651f7d.js")
R.m(586263)
module.exports=R.m(586263).exports
