var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/production/suppliers/recrop-search/route.js")
R.c("server/chunks/[root-of-the-server]__d33e8715._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_754c4630.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__0bc84f38._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/lib_product-suggestions_ts_6f46b2a7._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/ce889_server_app_api_production_suppliers_recrop-search_route_actions_133fb840.js")
R.m(21067)
module.exports=R.m(21067).exports
