var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/bulk-jobs/upload/route.js")
R.c("server/chunks/[root-of-the-server]__18c5c4e9._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_next-internal_server_app_api_bulk-jobs_upload_route_actions_67e835eb.js")
R.m(205805)
module.exports=R.m(205805).exports
