var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/1688-extractor/files/[name]/assign-spus/route.js")
R.c("server/chunks/[root-of-the-server]__2ad1bf78._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__4293de3b._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/ce889_server_app_api_1688-extractor_files_[name]_assign-spus_route_actions_46988418.js")
R.m(709717)
module.exports=R.m(709717).exports
