var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/email/send/route.js")
R.c("server/chunks/[root-of-the-server]__162a41d6._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_26b1624d.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_email_send_route_actions_baa9121e.js")
R.m(680893)
module.exports=R.m(680893).exports
