// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/admin">> = Specific
  const handler = {} as typeof import("../../app/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/candidates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/candidates/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/candidates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/customers">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/imports">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/lookbooks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/lookbooks/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/lookbooks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/lookbooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/lookbooks">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/lookbooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/projects">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/share-links/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/share-links/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/share-links/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/b2b/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/b2b/tasks">> = Specific
  const handler = {} as typeof import("../../app/app/b2b/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/digideal-campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/digideal-campaigns">> = Specific
  const handler = {} as typeof import("../../app/app/digideal-campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/digideal/deals-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/digideal/deals-manager">> = Specific
  const handler = {} as typeof import("../../app/app/digideal/deals-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/digideal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/digideal">> = Specific
  const handler = {} as typeof import("../../app/app/digideal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/digideal/product-delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/digideal/product-delivery">> = Specific
  const handler = {} as typeof import("../../app/app/digideal/product-delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/digideal/product-suggestions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/digideal/product-suggestions">> = Specific
  const handler = {} as typeof import("../../app/app/digideal/product-suggestions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/discovery/amazon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discovery/amazon">> = Specific
  const handler = {} as typeof import("../../app/app/discovery/amazon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/discovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/discovery">> = Specific
  const handler = {} as typeof import("../../app/app/discovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/automations">> = Specific
  const handler = {} as typeof import("../../app/app/email/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/chatwoot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/chatwoot">> = Specific
  const handler = {} as typeof import("../../app/app/email/chatwoot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/send/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/send">> = Specific
  const handler = {} as typeof import("../../app/app/email/send/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/settings">> = Specific
  const handler = {} as typeof import("../../app/app/email/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/templates/new">> = Specific
  const handler = {} as typeof import("../../app/app/email/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/email/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/email/templates">> = Specific
  const handler = {} as typeof import("../../app/app/email/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/exports">> = Specific
  const handler = {} as typeof import("../../app/app/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/letsdeal/deals-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/letsdeal/deals-manager">> = Specific
  const handler = {} as typeof import("../../app/app/letsdeal/deals-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/letsdeal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/letsdeal">> = Specific
  const handler = {} as typeof import("../../app/app/letsdeal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/market-trends/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/market-trends">> = Specific
  const handler = {} as typeof import("../../app/app/market-trends/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/my-lists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/my-lists">> = Specific
  const handler = {} as typeof import("../../app/app/my-lists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/nx-agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/nx-agents">> = Specific
  const handler = {} as typeof import("../../app/app/nx-agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/offerilla/deals-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/offerilla/deals-manager">> = Specific
  const handler = {} as typeof import("../../app/app/offerilla/deals-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/offerilla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/offerilla">> = Specific
  const handler = {} as typeof import("../../app/app/offerilla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/orders/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/orders/import">> = Specific
  const handler = {} as typeof import("../../app/app/orders/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/orders">> = Specific
  const handler = {} as typeof import("../../app/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/orders/resend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/orders/resend">> = Specific
  const handler = {} as typeof import("../../app/app/orders/resend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/production/bulk-processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/production/bulk-processing">> = Specific
  const handler = {} as typeof import("../../app/app/production/bulk-processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/production/draft-explorer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/production/draft-explorer">> = Specific
  const handler = {} as typeof import("../../app/app/production/draft-explorer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/production">> = Specific
  const handler = {} as typeof import("../../app/app/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products-design-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products-design-lab">> = Specific
  const handler = {} as typeof import("../../app/app/products-design-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/batch-image-editor/[batchId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/batch-image-editor/[batchId]/edit">> = Specific
  const handler = {} as typeof import("../../app/app/products/batch-image-editor/[batchId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/batch-image-editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/batch-image-editor">> = Specific
  const handler = {} as typeof import("../../app/app/products/batch-image-editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products">> = Specific
  const handler = {} as typeof import("../../app/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/pricing">> = Specific
  const handler = {} as typeof import("../../app/app/products/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/product-delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/product-delivery">> = Specific
  const handler = {} as typeof import("../../app/app/products/product-delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/products/spu/[spu]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/products/spu/[spu]">> = Specific
  const handler = {} as typeof import("../../app/app/products/spu/[spu]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/saved">> = Specific
  const handler = {} as typeof import("../../app/app/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/shopify/store-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/shopify/store-settings">> = Specific
  const handler = {} as typeof import("../../app/app/shopify/store-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/shopify/webshop-texts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/shopify/webshop-texts">> = Specific
  const handler = {} as typeof import("../../app/app/shopify/webshop-texts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/trend-research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/trend-research">> = Specific
  const handler = {} as typeof import("../../app/app/trend-research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/ui-kit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/ui-kit">> = Specific
  const handler = {} as typeof import("../../app/app/ui-kit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[token]">> = Specific
  const handler = {} as typeof import("../../app/share/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/[name]/assign-spus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files/[name]/assign-spus">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/[name]/assign-spus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/[name]/keywords/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files/[name]/keywords">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/[name]/keywords/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/[name]/preview-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files/[name]/preview-table">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/[name]/preview-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files/[name]">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files/merge">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/files">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/image-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/image-proxy">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688-extractor/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688-extractor/upload">> = Specific
  const handler = {} as typeof import("../../app/api/1688-extractor/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688/image-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688/image-search">> = Specific
  const handler = {} as typeof import("../../app/api/1688/image-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/1688/offer-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/1688/offer-detail">> = Specific
  const handler = {} as typeof import("../../app/api/1688/offer-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/file-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/file-upload">> = Specific
  const handler = {} as typeof import("../../app/api/admin/file-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/amazon/scrape-listing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/amazon/scrape-listing">> = Specific
  const handler = {} as typeof import("../../app/api/amazon/scrape-listing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/amazon/scrape-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/amazon/scrape-product">> = Specific
  const handler = {} as typeof import("../../app/api/amazon/scrape-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/activity">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/customers">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/import/1688-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/import/1688-product">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/import/1688-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/import/1688-shop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/import/1688-shop">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/import/1688-shop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/lookbooks/[id]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/lookbooks/[id]/items">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/lookbooks/[id]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/lookbooks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/lookbooks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/lookbooks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/lookbooks/items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/lookbooks/items/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/lookbooks/items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/lookbooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/lookbooks">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/lookbooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/notes">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/product-candidates/[id]/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/product-candidates/[id]/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/product-candidates/[id]/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/product-candidates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/product-candidates/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/product-candidates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/projects/[id]/candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/projects/[id]/candidates">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/projects/[id]/candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/projects/[id]/export-invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/projects/[id]/export-invoice">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/projects/[id]/export-invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/projects/[id]/export-offer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/projects/[id]/export-offer">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/projects/[id]/export-offer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/projects">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/share-links/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/share-links/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/share-links/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/share-links/[id]/selections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/share-links/[id]/selections">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/share-links/[id]/selections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/share-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/share-links">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/share-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/b2b/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/b2b/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/b2b/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/batch-image-editor/batches/[batchId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/batch-image-editor/batches/[batchId]">> = Specific
  const handler = {} as typeof import("../../app/api/batch-image-editor/batches/[batchId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/batch-image-editor/batches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/batch-image-editor/batches">> = Specific
  const handler = {} as typeof import("../../app/api/batch-image-editor/batches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/batch-image-editor/products/[productId]/images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/batch-image-editor/products/[productId]/images">> = Specific
  const handler = {} as typeof import("../../app/api/batch-image-editor/products/[productId]/images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]/download">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/logs/parallel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]/logs/parallel">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/logs/parallel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/logs/worker/[workerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]/logs/worker/[workerId]">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/logs/worker/[workerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]/start">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/[jobId]/stop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/[jobId]/stop">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/[jobId]/stop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/from-extractor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/from-extractor">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/from-extractor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bulk-jobs/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bulk-jobs/upload">> = Specific
  const handler = {} as typeof import("../../app/api/bulk-jobs/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/analysis">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/categories">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/export-excel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/export-excel">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/export-excel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/identical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/identical">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/identical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/product-suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/product-suggestions">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/product-suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/product-suggestions/source/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/product-suggestions/source">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/product-suggestions/source/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/sellers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/sellers">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/sellers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/views/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/views/items">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/views/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/digideal/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digideal/views">> = Specific
  const handler = {} as typeof import("../../app/api/digideal/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/actions">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/categories">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/identical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/identical">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/identical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/local-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/local-image">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/local-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/production/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/production/comments">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/production/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/production/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/production">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/production/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/wishlists/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/wishlists/items">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/wishlists/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/wishlists/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/wishlists/overview">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/wishlists/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/wishlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/wishlists">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/wishlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discovery/wishlists/shares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discovery/wishlists/shares">> = Specific
  const handler = {} as typeof import("../../app/api/discovery/wishlists/shares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/ai-edits/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/ai-edits/resolve">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/ai-edits/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/ai-edits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/ai-edits">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/ai-edits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/delete">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/download">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/files/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/files/content">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/files/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/files/copy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/files/copy">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/files/copy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]/cleanup">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]/list">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]/preview">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/spu-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]/spu-status">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/spu-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/[run]/tree/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/[run]/tree">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/[run]/tree/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders/merge">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/folders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/folders">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/folders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/google-lens/history/[id]/raw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/google-lens/history/[id]/raw">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/google-lens/history/[id]/raw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/google-lens/history/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/google-lens/history/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/google-lens/history/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/google-lens/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/google-lens/history">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/google-lens/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/google-lens/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/google-lens/records">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/google-lens/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/google-lens/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/google-lens/search">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/google-lens/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/auto-levels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/auto-levels">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/auto-levels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/order">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/refresh-scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/refresh-scores">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/refresh-scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/rename/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/rename">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/rename/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/replace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/replace">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/replace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/tag-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/tag-images">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/tag-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/images/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/images/undo">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/images/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/import">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/move">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/notes">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/products/bulk-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/products/bulk-update">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/products/bulk-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/products/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/products/delete">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/products/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/products/rewrite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/products/rewrite">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/products/rewrite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/products">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/products/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/products/update">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/products/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/publish">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/rename/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/rename">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/rename/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/sku/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/sku/generate">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/sku/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/sku/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/sku/status">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/sku/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/source-json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/source-json">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/source-json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/upload-urls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/upload-urls">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/upload-urls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/upload">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/ai-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants/ai-update">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/ai-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants/delete">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants/duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/replace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants/replace">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/replace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/variants/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/variants/update">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/variants/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drafts/zip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/zip">> = Specific
  const handler = {} as typeof import("../../app/api/drafts/zip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/chatwoot/templates/[templateId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/chatwoot/templates/[templateId]">> = Specific
  const handler = {} as typeof import("../../app/api/email/chatwoot/templates/[templateId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/chatwoot/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/chatwoot/templates">> = Specific
  const handler = {} as typeof import("../../app/api/email/chatwoot/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/chatwoot/templates/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/chatwoot/templates/versions">> = Specific
  const handler = {} as typeof import("../../app/api/email/chatwoot/templates/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/macros/[macroKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/macros/[macroKey]">> = Specific
  const handler = {} as typeof import("../../app/api/email/macros/[macroKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/macros/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/macros">> = Specific
  const handler = {} as typeof import("../../app/api/email/macros/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/send">> = Specific
  const handler = {} as typeof import("../../app/api/email/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/senders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/senders">> = Specific
  const handler = {} as typeof import("../../app/api/email/senders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/settings">> = Specific
  const handler = {} as typeof import("../../app/api/email/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/settings/signatures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/settings/signatures">> = Specific
  const handler = {} as typeof import("../../app/api/email/settings/signatures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/templates/[templateId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/templates/[templateId]">> = Specific
  const handler = {} as typeof import("../../app/api/email/templates/[templateId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/templates/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/templates/preview">> = Specific
  const handler = {} as typeof import("../../app/api/email/templates/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/templates">> = Specific
  const handler = {} as typeof import("../../app/api/email/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/templates/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/templates/versions">> = Specific
  const handler = {} as typeof import("../../app/api/email/templates/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/[id]/download">> = Specific
  const handler = {} as typeof import("../../app/api/exports/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/exports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/digideal/images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/digideal/images">> = Specific
  const handler = {} as typeof import("../../app/api/exports/digideal/images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/digideal/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/digideal/import">> = Specific
  const handler = {} as typeof import("../../app/api/exports/digideal/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/digideal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/digideal">> = Specific
  const handler = {} as typeof import("../../app/api/exports/digideal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/i18n/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/i18n">> = Specific
  const handler = {} as typeof import("../../app/api/i18n/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-trends/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-trends/latest">> = Specific
  const handler = {} as typeof import("../../app/api/market-trends/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-trends/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-trends/reports">> = Specific
  const handler = {} as typeof import("../../app/api/market-trends/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-trends/sites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-trends/sites">> = Specific
  const handler = {} as typeof import("../../app/api/market-trends/sites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-trends/vector/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-trends/vector/latest">> = Specific
  const handler = {} as typeof import("../../app/api/market-trends/vector/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nx-agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nx-agents">> = Specific
  const handler = {} as typeof import("../../app/api/nx-agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/email/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/email/send">> = Specific
  const handler = {} as typeof import("../../app/api/orders/email/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/export">> = Specific
  const handler = {} as typeof import("../../app/api/orders/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/import">> = Specific
  const handler = {} as typeof import("../../app/api/orders/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/import/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/import/template">> = Specific
  const handler = {} as typeof import("../../app/api/orders/import/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/imports/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/imports/download">> = Specific
  const handler = {} as typeof import("../../app/api/orders/imports/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/imports/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/imports/history">> = Specific
  const handler = {} as typeof import("../../app/api/orders/imports/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/resend/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/resend/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/resend/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/resend/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/resend/export">> = Specific
  const handler = {} as typeof import("../../app/api/orders/resend/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/resend">> = Specific
  const handler = {} as typeof import("../../app/api/orders/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/config">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/delete">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/download">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/export">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/history">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/import">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/manual/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/manual/template">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/manual/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/overview">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/recalculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/recalculate">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/recalculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/shipping/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/shipping/export">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/shipping/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/shipping/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/shipping/import">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/shipping/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pricing/threshold/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/threshold">> = Specific
  const handler = {} as typeof import("../../app/api/pricing/threshold/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/product-delivery/digideal/lists/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/product-delivery/digideal/lists/items">> = Specific
  const handler = {} as typeof import("../../app/api/product-delivery/digideal/lists/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/product-delivery/digideal/lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/product-delivery/digideal/lists">> = Specific
  const handler = {} as typeof import("../../app/api/product-delivery/digideal/lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/queue/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/queue/send">> = Specific
  const handler = {} as typeof import("../../app/api/production/queue/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/spu-pool/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/spu-pool/download">> = Specific
  const handler = {} as typeof import("../../app/api/production/spu-pool/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/spu-pool/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/spu-pool/summary">> = Specific
  const handler = {} as typeof import("../../app/api/production/spu-pool/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/spu-pool/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/spu-pool/upload">> = Specific
  const handler = {} as typeof import("../../app/api/production/spu-pool/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/manual-add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/manual-add">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/manual-add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/payload/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/payload/file">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/payload/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/payload/manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/payload/manual">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/payload/manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/payload/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/payload/retry">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/payload/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/recrop-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/recrop-search">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/recrop-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/selection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/selection">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/selection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/translate">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/production/suppliers/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/production/suppliers/variants">> = Specific
  const handler = {} as typeof import("../../app/api/production/suppliers/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[id]/description/rewrite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/description/rewrite">> = Specific
  const handler = {} as typeof import("../../app/api/products/[id]/description/rewrite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/actions">> = Specific
  const handler = {} as typeof import("../../app/api/products/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/advanced-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/advanced-search">> = Specific
  const handler = {} as typeof import("../../app/api/products/advanced-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/categories">> = Specific
  const handler = {} as typeof import("../../app/api/products/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/filters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/filters">> = Specific
  const handler = {} as typeof import("../../app/api/products/filters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/wishlists/convert-legacy-text/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/wishlists/convert-legacy-text">> = Specific
  const handler = {} as typeof import("../../app/api/products/wishlists/convert-legacy-text/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/wishlists/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/wishlists/items">> = Specific
  const handler = {} as typeof import("../../app/api/products/wishlists/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/wishlists/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/wishlists/merge">> = Specific
  const handler = {} as typeof import("../../app/api/products/wishlists/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/wishlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/wishlists">> = Specific
  const handler = {} as typeof import("../../app/api/products/wishlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/files/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/files/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/public/files/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/files/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/files/cleanup">> = Specific
  const handler = {} as typeof import("../../app/api/public/files/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/files/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/files/link">> = Specific
  const handler = {} as typeof import("../../app/api/public/files/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/files">> = Specific
  const handler = {} as typeof import("../../app/api/public/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/temp-images/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/temp-images/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/public/temp-images/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saved">> = Specific
  const handler = {} as typeof import("../../app/api/saved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sendpulse/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sendpulse/send">> = Specific
  const handler = {} as typeof import("../../app/api/sendpulse/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sendpulse/senders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sendpulse/senders">> = Specific
  const handler = {} as typeof import("../../app/api/sendpulse/senders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sendpulse/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sendpulse/templates">> = Specific
  const handler = {} as typeof import("../../app/api/sendpulse/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/ai-image-edit/guide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/ai-image-edit/guide">> = Specific
  const handler = {} as typeof import("../../app/api/settings/ai-image-edit/guide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/ai-image-edit/prompts/[promptId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/ai-image-edit/prompts/[promptId]">> = Specific
  const handler = {} as typeof import("../../app/api/settings/ai-image-edit/prompts/[promptId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/ai-image-edit/prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/ai-image-edit/prompts">> = Specific
  const handler = {} as typeof import("../../app/api/settings/ai-image-edit/prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/ai-image-edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/ai-image-edit">> = Specific
  const handler = {} as typeof import("../../app/api/settings/ai-image-edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/ai-image-edit/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/ai-image-edit/versions">> = Specific
  const handler = {} as typeof import("../../app/api/settings/ai-image-edit/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/discovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/discovery">> = Specific
  const handler = {} as typeof import("../../app/api/settings/discovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/api/settings/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/shopify-syncer/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/shopify-syncer/download">> = Specific
  const handler = {} as typeof import("../../app/api/settings/shopify-syncer/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/shopify-syncer/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/shopify-syncer/events">> = Specific
  const handler = {} as typeof import("../../app/api/settings/shopify-syncer/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/shopify-syncer/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/shopify-syncer/health">> = Specific
  const handler = {} as typeof import("../../app/api/settings/shopify-syncer/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/shopify-syncer/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/shopify-syncer/live">> = Specific
  const handler = {} as typeof import("../../app/api/settings/shopify-syncer/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/system/restart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/system/restart">> = Specific
  const handler = {} as typeof import("../../app/api/settings/system/restart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/system/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/system">> = Specific
  const handler = {} as typeof import("../../app/api/settings/system/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/users">> = Specific
  const handler = {} as typeof import("../../app/api/settings/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/zimage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/zimage">> = Specific
  const handler = {} as typeof import("../../app/api/settings/zimage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/share/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/share/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/share/[token]/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/[token]/select">> = Specific
  const handler = {} as typeof import("../../app/api/share/[token]/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/store-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/store-settings">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/store-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shopify/webshop-texts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/webshop-texts">> = Specific
  const handler = {} as typeof import("../../app/api/shopify/webshop-texts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/suppliers/product-suggestion-ai-scrape/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suppliers/product-suggestion-ai-scrape">> = Specific
  const handler = {} as typeof import("../../app/api/suppliers/product-suggestion-ai-scrape/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/suppliers/scrape-ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suppliers/scrape-ingest">> = Specific
  const handler = {} as typeof import("../../app/api/suppliers/scrape-ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trend-research/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trend-research">> = Specific
  const handler = {} as typeof import("../../app/api/trend-research/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
