var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/production/suppliers/payload/file/route.js")
R.c("server/chunks/[root-of-the-server]__d49be4bd._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__4293de3b._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/ce889_server_app_api_production_suppliers_payload_file_route_actions_c17dbc5a.js")
R.m(966295)
module.exports=R.m(966295).exports
