var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/resend/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__4f86ddea._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_orders_resend_[id]_route_actions_1a0f20b1.js")
R.m(567232)
module.exports=R.m(567232).exports
