var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/email/chatwoot/templates/[templateId]/route.js")
R.c("server/chunks/[root-of-the-server]__aa22d710._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_15903085.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/ce889_server_app_api_email_chatwoot_templates_[templateId]_route_actions_d61c7dc1.js")
R.m(120039)
module.exports=R.m(120039).exports
