var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/1688-extractor/files/route.js")
R.c("server/chunks/[root-of-the-server]__a326d181._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__4293de3b._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/_next-internal_server_app_api_1688-extractor_files_route_actions_541abc99.js")
R.m(246564)
module.exports=R.m(246564).exports
