var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/discovery/route.js")
R.c("server/chunks/[externals]_next_dist_3e40c974._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_f3437a29.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_discovery_route_actions_a0cca96c.js")
R.m(918956)
module.exports=R.m(918956).exports
