var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/b2b/projects/[id]/candidates/route.js")
R.c("server/chunks/[root-of-the-server]__f4811734._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/ce889_server_app_api_b2b_projects_[id]_candidates_route_actions_e546c18b.js")
R.m(109513)
module.exports=R.m(109513).exports
