var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/ai-image-edit/prompts/route.js")
R.c("server/chunks/[root-of-the-server]__1cf06c26._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/ce889_server_app_api_settings_ai-image-edit_prompts_route_actions_ae938067.js")
R.m(6176)
module.exports=R.m(6176).exports
