var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/digideal/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9175eedf._.js")
R.c("server/chunks/ssr/_5f6a9941._.js")
R.c("server/chunks/ssr/node_modules_next_dist_023b6025._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b021ab0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2e5d1b2c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f2037052._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_27de1937._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_digideal_page_actions_d4c8a0f8.js")
R.m(214147)
module.exports=R.m(214147).exports
