var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/drafts/ai-edits/resolve/route.js")
R.c("server/chunks/[root-of-the-server]__b18d6042._.js")
R.c("server/chunks/[root-of-the-server]__3d8dff81._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/lib_drafts_ts_8dd19890._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/lib_draft-ai-edits_ts_2f92daac._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_drafts_ai-edits_resolve_route_actions_41782ec4.js")
R.m(399869)
module.exports=R.m(399869).exports
