var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/nx-agents/route.js")
R.c("server/chunks/[externals]__5a2d3368._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_7667548a.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_nx-agents_route_actions_aee12357.js")
R.m(584646)
module.exports=R.m(584646).exports
