var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/b2b/lookbooks/[id]/items/route.js")
R.c("server/chunks/[root-of-the-server]__3efab35c._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_b2b_lookbooks_[id]_items_route_actions_9ba5cae5.js")
R.m(14748)
module.exports=R.m(14748).exports
