var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/app/saved/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__76503792._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_c368ea26._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b021ab0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2e5d1b2c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_f2037052._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_27de1937._.js")
R.c("server/chunks/ssr/_next-internal_server_app_app_saved_page_actions_00f247c0.js")
R.m(918109)
module.exports=R.m(918109).exports
