var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/products/[id]/description/rewrite/route.js")
R.c("server/chunks/[externals]__81659de8._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_f8017ce1.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/ce889_server_app_api_products_[id]_description_rewrite_route_actions_caeb3413.js")
R.m(783361)
module.exports=R.m(783361).exports
