var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/bulk-jobs/[jobId]/stop/route.js")
R.c("server/chunks/[root-of-the-server]__cb41a0f7._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/lib_drafts_ts_8dd19890._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/_next-internal_server_app_api_bulk-jobs_[jobId]_stop_route_actions_5db83a55.js")
R.m(569426)
module.exports=R.m(569426).exports
