var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/market-trends/latest/route.js")
R.c("server/chunks/[root-of-the-server]__9e793032._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_market-trends_latest_route_actions_e7c5d19a.js")
R.m(57008)
module.exports=R.m(57008).exports
