var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/ai-image-edit/route.js")
R.c("server/chunks/[externals]__3375e2f4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_e8644664.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/_next-internal_server_app_api_settings_ai-image-edit_route_actions_66a43663.js")
R.m(688284)
module.exports=R.m(688284).exports
