var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/1688-extractor/files/[name]/preview-table/route.js")
R.c("server/chunks/[externals]__7749818b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_ccbe5560.js")
R.c("server/chunks/[root-of-the-server]__4293de3b._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_3577e4f1._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/ce889_server_app_api_1688-extractor_files_[name]_preview-table_route_actions_3f98a0b5.js")
R.m(645036)
module.exports=R.m(645036).exports
